---
- name: "practicing filters with examples"
  hosts: local
  connection: local
  tasks:
  - name: "default variables"
    ansible.builtin.debug:
      msg: "{{name | default('HANUMAN')}}"
  - name: "strings to lists conversion"
    vars:
      Technologies: "DevOps,Java,Python,AWS"
    ansible.builtin.debug:
      msg: "{{ Technologies | split(',')}}"
  - name: "dictionaries to list conversion"
    vars:
      vehicles:
        two_wheeler: bus
        four_wheeler: car
    ansible.builtin.debug:
      msg: "types of vehicles are : {{vehicles | dict2items}}"