---
- name: "practicing filters with examples"
  hosts: local
  connection: local
  tasks:
  - name: "default variables"
    ansible.builtin.debug:
      msg: "{{name | default('HANUMAN')}}"
  - name: "strings to lists conversion"
    vars:
      Technologies: "DevOps,Java,Python,AWS"
    ansible.builtin.debug:
      msg: "{{ Technologies | split(',')}}"
  - name: "dictionaries to list conversion"
    vars:
      vehicles:
        two_wheeler: bus
        four_wheeler: car
    ansible.builtin.debug:
      msg: "types of vehicles are : {{vehicles | dict2items}}"

  - name: "list to dictionaries conversion" 
    vars:  
      options:
        - key: Application
          value: payment
        - key: Environment
          value: dev
    ansible.builtin.debug:
      msg: "tags are {{options | items2dict}}"
  
  - name: "read yaml and take into file"
    ansible.builtin.set_fact:
      file: "{{lookup('file', './vars.yaml') | from_yaml}}"
  - name: "yaml to json conversion"
    ansible.builtin.debug:
     msg: "{{ file | to_json}}"

  - name: "copy the converted json file"
    ansible.builtin.copy:
      dest: "./converted.json"
      content: "{{ file | to_nice_json}}"


