---
- name: "looping the names"
  hosts: local
  connection: local
  tasks:
  - name: "print names through loop"
    debug:
      msg: "{{item}}"
    loop:
      - hanuman
      - ram
      - krishna
  - name: "install packages based on state"
    package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
     - { name: "nginx", state: "latest" }
     - { name: "zip", state: "latest" }
