---
- name: "looping the names"
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: "print names through loop"
    debug:
      msg: "{{item}}"
    loop:
      - hanuman
      - ram
      - krishna
  - name: "install packages based on state"
    package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
      - {name: "nginx", state: "present"}
      - {name: "zip", state: "present"}
  - name: " service check"
    service:
      name: "{{item.name}}"
      state: "{{item.state}}"
      enabled: yes
    loop:
      - {name: "nginx", state: "started"}
      - {name: "zip", state: "started"}

